Website/views.py
"""
Created by Jesse Scully
Date: 15/09/2025
Influenced by: Python Website Full Tutorial by Tech With Tim
Link: https://www.youtube.com/watch?v=dam0GPOAvVI
"""

from flask import Blueprint, render_template, request, flash, jsonify, redirect, url_for, request
from flask_login import login_required, current_user
from datetime import datetime
from .models import User_details, performance_entries
from . import db
import json

views = Blueprint('views', __name__)

@views.route('/home', methods=['GET', 'POST'])
# Navigate to dashboard if button is pressed
@login_required
def home():
    if request.method == 'POST':
        return redirect(url_for('views.dashboard'))
    return render_template("home.html", boolean = True)

# Establish the dashboard
@views.route('/dashboard')
@login_required
def dashboard():
    # Get details from profile edit page
    player = User_details.query.first()
    # Query the entries from the database for only 2025
    all_entries = performance_entries.query.filter(
        performance_entries.time >= datetime(2025, 1, 1),
        performance_entries.time < datetime(2026, 1, 1)
    )
    # Call the calculate win rate function
    win_rate_2025 = calculate_win_rate(all_entries)
    # Call the function for win rates for 2025 chart
    return render_template('dashboard.html', player=player, win_rate_2025=win_rate_2025)

# Designate a route to go to the performance entry edit page
@views.route('/performance_entry')
@login_required
def pe_route():
    return render_template('performance_entry.html')

# Designate a route to go to the coaching entry edit page
@views.route('/coaching_entry')
@login_required
def ce_route():
    return render_template('coaching_entry.html')

# Designate a route to go back to the dashboard that can be used by multiple pages
@views.route('/c_dashboard', methods=["GET","POST"])
@login_required
def to_dashboard():
    return redirect(url_for('views.dashboard'))

# Designate a route to go to the profile edit page
# Retrieve data
@views.route('/profile_edit')
@login_required
def render_profile_edit():
    return render_template('profile_edit.html')

# Code influenced by: https://www.digitalocean.com/community/tutorials/how-to-use-web-forms-in-a-flask-application?
# Submit profile details, save data and redirect to the dashboard
@views.route('/dashboard/edit', methods=['POST'])
def edit_details():
    if request.method == 'POST':
        player_name = request.form.get('player_name')
        player_description = request.form.get('player_description')

        player = User_details.query.first()

        # Insert a brand new entry for player
        if player is None:
            player = User_details(name=player_name, description=player_description)
            db.session.add(player)
        # If not empty, replace it with the new entry
        else:
            player.name = player_name
            player.description = player_description

        db.session.commit()
        return redirect(url_for('views.dashboard'))

# Submit Performance Entries, save data and redirect to dashboard
@views.route('/dashboard/performance_entry', methods=['POST'])
def performance_details():
    player_date = request.form.get('datepicker')
    player_date = datetime.strptime(player_date, '%Y-%m-%d')
    player_wins = int(request.form.get('player_wins', 0))
    player_losses = int(request.form.get('player_losses', 0))
    player_intensity = int(request.form.get('player_intensity', 0))

    # Figure out if the date was inserted in a specific months using if statements
    # For each if statement, add it to the corresponding month and then calculate new monthly win rate

    # Insert as part of the player_performance variable when i write the code in

    # Immediately insert new entries without replacing the original
    player_performance = performance_entries(wins=player_wins, losses=player_losses, intensity=player_intensity, time=player_date)


    db.session.add(player_performance)
    db.session.commit()
    return redirect(url_for('views.dashboard'))

# Create a function that calculates win rates for you
def calculate_win_rate(all_entries):
    wins_by_month = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    games_by_month = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

    # How to fill the buckets...
    # Get month from entry date
    # Convert month to array indexd
    # Add session total into that month

    # Calculate the actual 12 winrates
    win_rates = []
    for index in :
        if games_by_month[index] == 0:
            win_rate = 0
        else:
            win_rate = wins_by_month[index] / games_by_month[index]
            win_rates.append(win_rate)
    return win_rates





    # Calculate the win rate for each month
    # Use a for loop

Website/templates/add_entry.html
<!--
Created by Jesse Scully
Date: 29/09/2025
Influenced by:
-->

<!--
1. Focus on adding an entry for match performance for the day
2. Put a calendar to select a specific date
3. Badminton Social Game Entries should include the following:
- Game 1... + additional options to add more games
- Total wins and losses for the day
- Personal overall performance or feeling (positive or negative)
- Additional notes, comments or things you want to improve on
- E.g. "Need to work on my smashes", "My mixed doubles was good today"
-->

Website/templates/base.html
<!--
Created by Jesse Scully
Date: 15/09/2025
Influenced by: Python Website Full Tutorial by Tech With Tim
Link: https://www.youtube.com/watch?v=dam0GPOAvVI
-->

<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <!-- Import the Bootstrap CSS to be used throughout -->
        <!-- Update to latest version of bootstrap 5 -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" crossorigin="anonymous"/>
        <!-- Link to css file in the static folder -->
        <link rel="stylesheet" href="{{url_for('static', filename='bootstrap.min.css')}}">
        <!-- Chart.JS -->
        <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

        <title>
            {% block title %}Home{% endblock %}
        </title>
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <button 
                class="navbar-toggler"  
                type="button" v 
                data-toggle="collapse" 
                data-target= "#navbar"
            >
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbar">
                <div class="navbar-nav">
                    <!--Only show certain buttons if user is logged in or not-->
                    {% if current_user.is_authenticated %}
                    <a class="nav-item nav-link" id="home" href="/home">Home</a>
                    <a class="nav-item nav-link" id="dashboard" href="/dashboard">Dashboard</a>
                    <a class="nav-item nav-link" id="logout" href="/logout">Logout</a>
                    {% else %}
                    <a class="nav-item nav-link" id="login" href="/login">Login</a>
                    <a class="nav-item nav-link" id="signUp" href="/sign-up">Sign Up</a>
                    {% endif %}
                </div>
            </div>
        </nav>
        

        <!-- Uses flask to enable flash messages for auth.py file -->
        {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            {% for category, message in messages %}
            {% if category == 'err' %}
            <div class="alert alert-danger alter-dismissable fade show" role="alert">
                {{ message }}
                <button type="button" class="close" data-dismiss="alert">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            {% else %}
            <div class="alert alert-success alter-dismissable fade show" role="alert">
                {{ message }}
                <button type="button" class="close" data-dismiss="alert">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            {% endif %}
            {% endfor %}
        {% endif %}
        {% endwith %}

        <div class="container">
            {% block content %}
            {% endblock %}
        </div>
        <script
        src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"
        ></script>
        <script
        src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"
        ></script>
        <script
        src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"
        ></script>
        <!-- Share Javascript functions across all html files -->
        <script
            type="text/javascript"
            src="{{ url_for('static', filename='dashboard.js')}}">
        </script>
    </body>
</html>

Website/templates/dashboard.html
<!--
Created by Jesse Scully
Date: 28/09/2025
Influenced by:
-->

{% extends "base.html" %}
{% block title %}Dashboard{% endblock %}

{% block content %}

<!-- Dashboard layout basics based on: https://www.w3schools.com/bootstrap5/bootstrap_get_started.php -->

<br>
<h1 align="left">My Dashboard</h1> <br>

<!-- Code influenced by: https://www.w3schools.com/bootstrap5/bootstrap_cards.php -->
<!-- Positioning code based on: https://getbootstrap.com/docs/5.3/utilities/position/-->
<div class="container mt-3 position-relative">
  <h2>Profile</h2>
  <br>
<form>

<a href="{{ url_for('views.render_profile_edit') }}">
<button type="button" class="btn btn-primary mb-2">Edit</button>
</a>

<div class="position-absolute
            top-0
            start-50">
  <h1> Performance </h1>
  <h2> Win Rate for 2025 </h2>
  <body>
  <canvas id="lineChart" width="900" height="400"></canvas>
  
  
  <script>
    // Display win percentage rate from performance entries
    // Code influenced by: https://www.gitauharrison.com/articles/data-visualization-with-flask-and-chartjs
    const ctx = document.getElementById('lineChart').getContext('2d');
    const myChart = new Chart(ctx, {
        type: 'line',
        data: {
            labels: ['Jan', 'Feb','Mar','Apr', 'May','Jun','July', 'Aug','Sep','Oct', 'Nov','Dec'],
            // Dataset will be win rates per month
            datasets: [{
                label: 'Win Rate per Month',
                data: [12, 19, 3, 5, 2, 3],
            }]
        },
        options: {
            scales: {
                y: {
                    beginAtZero: true
                }
            },
        },
        
    });
  </script>

</body>
</div>

  <div class="card text-white bg-secondary mb-3" style="width:320px">
    <!-- Need to insert an image from the user and upload successfully 
    Or can give choices to the user and select a several images-->
    <img class="card-img-top" src="{{url_for('static', filename='Default_Image.jpg')}}" alt="Card image" style="width:100%">
    
    <div class="card-body">
    
    <label> Name </label>
    <input type="text" class="form-control" name="name" value="{{ player.name }}" readonly><br>
        
    <label> Player Description </label>
    <input type="text" class="form-control mb-4" name="description" value="{{ player.description }}" readonly>

    <a href="{{ url_for('views.pe_route') }}">
      <button type="button" class="btn btn-primary mb-2">Add Performance Entry</button>
    </a>
    
    </div>
  </div>

</div>






<!-- 
1. Add a default picture for users and then give option to upload a picture
2. Make a button to enter an entry for the day for day performance for badminton games
3. Can make a separate button for coaching entries
 -->

{% endblock %}

Website/templates/home.html
<!--
Created by Jesse Scully
Date: 15/09/2025
Influenced by: Python Website Full Tutorial by Tech With Tim
Link: https://www.youtube.com/watch?v=dam0GPOAvVI
-->

{% extends "base.html" %}
{% block title %}Home{% endblock %}

{% block content %}

<br>
<form method="POST">
    <br />
    <h1 align="left">Select Sport</h1>
    <br>
    <body>
    <button class="btn btn-primary btn-lg">Badminton</button>
    </body>
</form>
{% endblock %}

Website/templates/login.html
<!--
Created by Jesse Scully
Date: 15/09/2025
Influenced by: Python Website Full Tutorial by Tech With Tim
Link: https://www.youtube.com/watch?v=dam0GPOAvVI
-->

{% extends "base.html" %}
{% block title %}Login{% endblock %}

{% block content %}

<form method="POST">
    <br />
    <h3 align="center">Login</h3>
    <div class="form-group">
        <label for="email">Email Address</label>
        <input 
            type="email" 
            class="form-control" 
            id="email" 
            name="email" 
            placeholder="Enter email"
        />
    </div>

    <div class="form-group">
        <label for="password">Password</label>
        <input 
            type="password" 
            class="form-control" 
            id="password" 
            name="password" 
            placeholder="Enter password"
        />
    </div>

    <br />
    <button type="submit" class="btn btn-primary">Login</button>
</form>

{% endblock %}

Website/templates/performance_entry.html
<!--
Created by Jesse Scully
Date: 29/09/2025
Influenced by:
-->

<!--
1. Focus on adding an entry for match performance for the day
2. Put a calendar to select a specific date
3. Badminton Social Game Entries should include the following:
- Game 1... + additional options to add more games
- Total wins and losses for the day
- Personal overall performance or feeling (positive or negative)
- Additional notes, comments or things you want to improve on
- E.g. "Need to work on my smashes", "My mixed doubles was good today"
-->

{% extends "base.html" %}
{% block title %}Dashboard{% endblock %}

{% block content %}

<br>
<h1 align="left">Performance Entry</h1>



<!-- This form will submit all data to database to be displayed on the graphs dashboard -->
<form method="POST" action ="{{ url_for('views.performance_details')}}">
    <!-- Add a calendar -->
    <!-- Code taken from this tutorial: https://www.youtube.com/watch?v=XgUYftRJHPY -->
    <label for="datepicker"> Select Date: </label>
    <input type="date" id="datepicker" name="datepicker">
    <br><br>

    <label for="wins">Total Wins for the Day: </label>
    <input type="number" class="form-control" id="wins" name="player_wins" value=""><br>
        
    <label for="losses"> Total Losses for the Day:</label><br>
    <input type="number" class="form-control mb-4" id="losses" name="player_losses" value="">

    <fieldset>
      <label for="customRange3" class="form-label">Intensity Level</label>
      <input type="range" class="form-range" name="player_intensity" min="1" max="10" step="1" id="customRange3">
    </fieldset>

    <button type="submit" class="btn btn-primary">Submit</button>

</form>
{% endblock %}

Website/templates/profile_edit.html
{% extends "base.html" %}
{% block title %}Profile Edit{% endblock %}

{% block content %}
 
<br>
<h1 align="left">Profile Edit</h1>

<!-- Code influenced by: https://www.digitalocean.com/community/tutorials/how-to-use-web-forms-in-a-flask-application?-->
<form method="POST" action="{{ url_for('views.edit_details')}}">
    <label for="name">Name: </label>
    <input type="text" name="player_name" class="form-control" 
            value="{{ name }}"></input> <br>
        
    <label for="description">Player Description:</label>
    <input type="text" name="player_description" class="form-control" 
            value="{{ description }}"></input> <br>

    <button type="submit" class="btn btn-primary">Submit</button>
</form>

{% endblock %}

Website/templates/sign_up.html
<!--
Created by Jesse Scully
Date: 15/09/2025
Influenced by: Python Website Full Tutorial by Tech With Tim
Link: https://www.youtube.com/watch?v=dam0GPOAvVI
-->

{% extends "base.html" %}
{% block title %}Sign up{% endblock %}

{% block content %}

<form method="POST">
    <br />
    <h3 align="center">Sign Up</h3>
    <div class="form-group">
        <label for="email">Email Address</label>
        <input 
            type="email" 
            class="form-control" 
            id="email" 
            name="email" 
            placeholder="Enter email"
        />
    </div>

    <div class="form-group">
        <label for="firstName">First Name</label>
        <input 
            type="text" 
            class="form-control" 
            id="firstName" 
            name="firstName" 
            placeholder="Enter first name"
        />
    </div>

    <div class="form-group">
        <label for="password1">Password</label>
        <input 
            type="password" 
            class="form-control" 
            id="password1" 
            name="password1" 
            placeholder="Enter password"
        />
    </div>

    <div class="form-group">
        <label for="password2">Password (Confirm)</label>
        <input 
            type="password" 
            class="form-control" 
            id="password2" 
            name="password2" 
            placeholder="Confirm password"
        />
    </div>
    <br />
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

{% endblock %}